name: Build and GitOps

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: ghcr.io/abhinav211/gitops-demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Image
        run: docker push $IMAGE_NAME:${{ github.sha }}

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: abhinav211/gitops-demo-manifests
          token: ${{ secrets.GH_PAT }}
          path: gitops

      - name: Update Image Tag
        run: |
          sed -i "s|image: .*|image: $IMAGE_NAME:${{ github.sha }}|" gitops/dev/rollout.yaml

      - name: Commit and Push
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "Update image to ${{ github.sha }}" || exit 0

          git push
